services:
  python34-app:
    image: python34-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python34-dev
    working_dir: /app
    volumes:
      - .:/app
    tty: true
